### ISSUE TITLE
Please bump version number 1.6.13

### ISSUE THREAD

**Issue by grettke** [xml-rpc-el/xml-rpc-el#9]
[This change](https://github.com/hexmode/xml-rpc-el/pull/8/commits/8ee416cb7644eef4ca8edda5ea79b1c670555ad0) enabled Emacs 25 support directly instead of relying on a patched version. It is great news!

Please make a release so that conservative package can rely on 1.6.13 instead of getting latest.

Thanks and have a great day.

**Comment by skangas** [comment]
Any updates on this?

Thanks.

**Comment by hexmode** [comment]
Sorry this took so long.

**Comment by grettke** [comment]
@hexmode Thanks!

**Comment by skangas** [comment]
Thanks for doing that.

You might want to update the ";; Version:" header in the file too.
